accounts/urls.py
from django.urls import path
from django.contrib.auth import views as auth_views
from . import views

app_name = 'accounts'

urlpatterns = [
    path('login/',auth_views.LoginView.as_view(template_name='accounts/login.html'),name='login'),
    path('logout/',auth_views.LogoutView.as_view(),name='logout'),
    path('signup/',views.SignUp.as_view(),name='signup'),
]

groups/urls.py
from django.urls import include, path
from . import views

app_name = 'groups'

urlpatterns = [
    path('',views.ListGroups.as_view(),name='all'),
    path('new/',views.CreateGroup.as_view(),name='create'),
    path("posts/in/<slug:slug>",views.SingleGroup.as_view(), name="single"),
    
]

imperium/urls.py
import django
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', views.HomePage.as_view(),name='home'),
    path('accounts/',include('accounts.urls',namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('test/',views.TestPage.as_view(),name='test'),
    path('thanks/',views.ThanksPage.as_view(),name='thanks'),
]

accounts/models.py
from django.db import models
from django.contrib import auth

# Create your models here.
class User(auth.models.User,auth.models.PermissionsMixin):


    def __str__(self) -> str:
        return "@{}".format(self.username)

        

groups/models.py
from django.db import models
from django.utils.text import slugify
# Create your models here.
import misaka

from django.contrib.auth import get_user_model

User = get_user_model()

from django import template
register = template.Library()

class Group(models.Model):
    name = models.CharField(max_length=255,unique=True)
    slug = models.SlugField(allow_unicode=True,unique=True)
    description = models.TextField(blank=True,default='')
    description_html = models.TextField(editable=False,default='',blank=True)
    members = models.ManyToManyField(User,through='GroupMember')

    def __str__(self):
        return self.name

    def save(self,*args, **kwargs):
        self.slug = slugify(self.name)
        self.description_html = misaka.html(self.description)

    def get_absolute_url(self):
        return reverse('groups:single', kwargs={'slug': self.slug})

    class Meta:
        ordering = ['name']

class GroupMember(models.Model):
    group = models.ForeignKey(Group,related_name='memberships')
    user = models.ForeignKey(User,related_name='user_groups')
    
    def __str__(self):
        return self.user.username

    class Meta:
        unique_together = ('group','user')

posts/models.py
from enum import unique
from django.core.checks import messages
from django.db import models
from django.urls import reverse
from django.conf import settings
from django.contrib.auth import get_user_model

import misaka

from groups.models import Group
# Create your models here.
#POST MODELS 

User = get_user_model()

class Post(models.Model):
    user = models.ForeignKey(User, related_name='posts')
    created_at = models.DateTimeField(auto_now=True)
    message = models.TextField()
    message_html = models.TextField(editable=False)
    group = models.ForeignKey(Group,related_name='posts',null=True,blank=True)

    def __str__(self):
        return self.message

    def save(self,*args,**kwargs):
        self.message_html = misaka.html(self.message)
        super().save(*args,**kwargs)


    def get_absolute_url(self):
        return reverse("posts:single", kwargs={'username': self.user.username,'pk':self.pk})
    
    
    class Meta:
        ordering = ['-created_at']
        unique_together = ['user','message']

accounts/forms.py
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

class UserSignUpForm(UserCreationForm):

    class Meta:
        model = get_user_model()
        fields = ('username','first_name','last_name','email','password1','password2')

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self.fields['username'].label = 'Display Name'
        self.fields['first_name'].label = 'First Name'
        self.fields['last_name'].label = 'Last Name'
        self.fields['email'].label = 'Email Address'
        

accounts/views.py
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views.generic import CreateView

from . import forms
# Create your views here.

class SignUp(CreateView):
    form_class = forms.UserSignUpForm
    success_url = reverse_lazy('login')
    template_name = 'accounts/signup.html'

groups/views.py
from groups.models import Group
from django.db import models
from django.shortcuts import render

# Create your views here.
from django.contrib.auth.mixins import LoginRequiredMixin,PermissionRequiredMixin

from django.urls import reverse
from django.views import generic 

class CreateGroup(LoginRequiredMixin,generic.CreateView):
    fields = ('name','description')
    model = Group

class SingleGroup(generic.DetailView):
    model = Group

class ListGroups(generic.ListView):
    model = Group

imperium/views.py
from django.views.generic import TemplateView

class HomePage(TemplateView):
    template_name = 'index.html'

class TestPage(TemplateView):
    template_name = 'test.html'

class ThanksPage(TemplateView):
    template_name = 'thanks.html'
    

posts/views.py
from django.shortcuts import render

# Create your views here.

accounts/templates/accounts/login.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <h1>Login</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Sign up" class="btn btn-default">
    </form>
{% endblock content %}

accounts/templates/accounts/signup.html
{% extends 'base.html' %}
{% load bootstrap4 %}

{% block content %}
    <h1>Sign Up</h1>
    <form method="POST">
        {% csrf_token %}
        {% bootstrap_form form %}
        <input type="submit" value="Sign up" class="btn btn-default">
    </form>
{% endblock content %}

groups/templates/groups/group_base.html
{% extends 'base.html' %}

{% block content %}
<div class="Container">
    <div class="row">
        {% block pregroup %}{% endblock pregroup %}
        {% block group_content %}{% endblock group_content %}
        {% block postgroup %}{% endblock postgroup %}
        
    </div>
</div>

{% endblock content %}

groups/templates/groups/group_detail.html
{% extends 'groups/group_base.html' %}

{% block pregroup %}
<h1>{{group.name}}</h1>
<h2>Member Count: {{ group.members.count }}</h2>

<div class="content">
    {% if user in group.members.all %}


    <!-- give the user the option to leave  -->
    <a href="{url 'groups:leave' slug=group.slug }" 
    class="btn btn-lg btn-fill btn-warning ">Leave Group</a>
    {% else %}

    <!-- give the user the option to join  -->
    <a href="{url 'groups:join' slug=group.slug }" 
    class="btn btn-lg btn-fill btn-warning ">Join this Group</a>

    {% endif %}


</div>
{% endblock pregroup %}

{% block group_content %}
<div class="col-md-8">
    {% if group.posts.count == 0 %}
        <h2>No post in this group yet</h2>
        <p>Be the first one to do so!</p>
    {% else %}
        {% for post in group.post.all  %}
            {% include "posts/_post.html" %}

        {% endfor %}
    {% endif %}

</div>

{% endblock group_content %}

groups/templates/groups/group_form.html
{% extends 'groups/group_base.html' %}

{% load bootsrap4 %}

{% block group_content %}
<h4>
    Create a new group
</h4>

<form action="{% url 'groups:create' %}" method="post" id="groupForm">

    {% csrf_token %}
    {% bootsrap_form form %}
    <input type="submit" class="btn btn-primary btn-large" value="Create">
</form>
{% endblock group_content %}

groups/templates/groups/group_list.html
{% extends 'group/group_base.html' %}

{% block pregroup %}
<div class="col-md-4">
    <div class="content">
        {% if user.is_authenticated %}
        <h2>Welcome Back!</h2>
        <a href="{% url 'posts:for_user' username=user.username %}">
        @{{user.username}}
        </a>
        {% endif %}
        <h2>Groups</h2>
        <p>Welcome to the groups page!</p>
    </div>
        {% if user.is_authenticated %}
        <a href="{% url 'groups:create' %}" class="btn btn-md btn-fill btn-warning">
            <span>Create a new Group!</span>
        </a>
            
        {% endif %}

</div>
{% endblock pregroup %}

{% block group_content %}
<div class="col-md-8">
    <div class="list-group">
        {% for group in object_list %}
        <a href="{% url 'groups:single' slug=group.slug %}">
        <h3 class="title list-group-item-heading">{{group.name}}</h3>
        <div class="list-group-item-text container-fluid">
            {{group.description_html|safe}}
            <div class="row">
                <div class="col-md-4">
                    <span class="badge">{{group.members.count}}</span>
                    member{{group.members.count|pluralize}}
                </div>
                <div class="col-md-4">
                    <span class="badge">
                        {{group.posts.count}}
                    </span>
                    post{{group.posts.count|pluralize}}
                </div>
            </div>
        </div>
        </a>
        {% endfor %}
    </div>
</div>
{% endblock group_content %}

templates/base.html
<!DOCTYPE html>
{% load static %}
<html lang="en">


<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Imperium</title>
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css"
        integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.min.js"
        integrity="sha384-cVKIPhGWiC2Al4u+LWgxfKTRIcfu0JTxR+EQDz/bgldoEyl4H0zUF0QKbrJ0EcQF"
        crossorigin="anonymous"></script>

    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@100&display=swap" rel="stylesheet">

    <link rel="stylesheet" href="{% static 'simplesocial/css/master.css' %}">



</head>

<body>
    <nav class="navbar navbar-expand-lg navbar-light bg-light" role='navigation' id='navbar'>
        <a class="navbar-brand" href="#">Navbar w/ text</a>
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarText"
            aria-controls="navbarText" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    <a class="nav-link" href="{% url 'home' %}">Home <span class="sr-only">(current)</span></a>
                </li>
                {% if user.is_authenticated %}
                <li class="nav-item">
                    <a class="nav-link" href="#">Post</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Groups</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="#">Create Group</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:logout' %}">Log Out</a>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="#">Groups</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:login' %}">Log In</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'accounts:signup' %}">Sign Up</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </nav>

    <div class="container mycontent">
        {% block content %}



        {% endblock content %}
    </div>


</body>

</html>

templates/index.html
{% extends 'base.html' %}

{% block content %} 
<h1>Welcome to Imperium!</h1>
{% endblock content %}
   

templates/test.html
{% extends 'base.html' %}

{% block content %}
<h1>Welcome User!</h1>
{% endblock content %}

templates/thanks.html
{% extends 'base.html' %}

{% block content %}
<h1>Thank You For Visiting, Come Again!</h1>
{% endblock content %}